#!/usr/bin/env ruby
require 'english'
require 'optparse'

commands = %w(update upgrade)

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: brew upup [options]'

  opts.on('-c', '--cleanup', "Run 'brew cleanup' command after upgrading") do |c|
    options[:clean] = c
    commands << 'cleanup'
  end

  opts.on('-q', '--quiet', 'Run quietly') do |q|
    options[:quiet] = q
  end
end.parse!

def callbrew(command, isQuiet)
  if isQuiet
    `brew #{command}`
  else
    puts "brew #{command}"
    system("brew #{command}")
  end
  abort("brew #{command} failed") if $CHILD_STATUS.to_i != 0
end

commands.each do |command|
  callbrew(command, options[:quiet])
end
